#
# Copyright John Reid 2007
#

"""
Code for unigene data.

http://www.ncbi.nlm.nih.gov/sites/entrez?db=unigene
"""

species = {
        "Aae" : "Aedes aegypti",
        "Aga" : "Anopheles gambiae",
        "Ame" : "Apis mellifera",
        "Afp" : "Aquilegia formosa x Aquilegia pubescens",
        "At" : "Arabidopsis thaliana",
        "Bmo" : "Bombyx mori",
        "Bt" : "Bos taurus",
        "Bfl" : "Branchiostoma floridae",
        "Bna" : "Brassica napus",
        "Cel" : "Caenorhabditis elegans",
        "Cfa" : "Canis familiaris",
        "Cre" : "Chlamydomonas reinhardtii",
        "Cin" : "Ciona intestinalis",
        "Csa" : "Ciona savignyi",
        "Csi" : "Citrus sinensis",
        "Cpo" : "Coccidioides posadasii",
        "Dr" : "Danio rerio",
        "Ddi" : "Dictyostelium discoideum",
        "Dm" : "Drosophila melanogaster",
        "Fne" : "Filobasidiella neoformans",
        "Fhe" : "Fundulus heteroclitus",
        "Gga" : "Gallus gallus",
        "Gac" : "Gasterosteus aculeatus",
        "Gmo" : "Gibberella moniliformis",
        "Gma" : "Glycine max",
        "Ghi" : "Gossypium hirsutum",
        "Gra" : "Gossypium raimondii",
        "Han" : "Helianthus annuus",
        "Hs" : "Homo sapiens",
        "Hv" : "Hordeum vulgare",
        "Hma" : "Hydra magnipapillata",
        "Lsa" : "Lactuca sativa",
        "Lco" : "Lotus corniculatus",
        "Les" : "Lycopersicon esculentum",
        "Mfa" : "Macaca fascicularis",
        "Mmu" : "Macaca mulatta",
        "Mgr" : "Magnaporthe grisea",
        "Mdo" : "Malus x domestica",
        "Mtr" : "Medicago truncatula",
        "Mte" : "Molgula tectiformis",
        "Mm" : "Mus musculus",
        "Ncr" : "Neurospora crassa",
        "Omy" : "Oncorhynchus mykiss",
        "Ocu" : "Oryctolagus cuniculus",
        "Os" : "Oryza sativa",
        "Ola" : "Oryzias latipes",
        "Oar" : "Ovis aries",
        "Ppa" : "Physcomitrella patens",
        "Pin" : "Phytophthora infestans",
        "Pgl" : "Picea glauca",
        "Psi" : "Picea sitchensis",
        "Ppr" : "Pimephales promelas",
        "Pta" : "Pinus taeda",
        "Pba" : "Populus balsamifera",
        "Ptp" : "Populus tremula x Populus tremuloides",
        "Rn" : "Rattus norvegicus",
        "Sof" : "Saccharum officinarum",
        "Ssa" : "Salmo salar",
        "Sja" : "Schistosoma japonicum",
        "Sma" : "Schistosoma mansoni",
        "Stu" : "Solanum tuberosum",
        "Sbi" : "Sorghum bicolor",
        "Spu" : "Strongylocentrotus purpuratus",
        "Ssc" : "Sus scrofa",
        "Tru" : "Takifugu rubripes",
        "Tgo" : "Toxoplasma gondii",
        "Tca" : "Tribolium castaneum",
        "Ta" : "Triticum aestivum",
        "Vvi" : "Vitis vinifera",
        "Xl" : "Xenopus laevis",
        "Str" : "Xenopus tropicalis",
        "Zm" : "Zea mays",
}
