#!/bin/bash -ex

SELF=$(readlink -f $BASH_SOURCE)
SELFDIR=$(dirname $SELF)

cd $HOME/Data/serialised

parse-transfac
rm factor_synonyms.txt
factor-synonyms
$SELFDIR/update-pssm-cache
calculate-pssm-likelihoods
# calculate-normalisations  # Can only run this when we have a species_hmm.txt
